"""Add location & distance range pref

Revision ID: a15b1085162f
Revises: 2427de7ddc58
Create Date: 2021-05-03 17:29:59.050382

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'a15b1085162f'
down_revision = '2427de7ddc58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column(
        'location',
        geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'),
        nullable=True)
    )
    op.add_column('users', sa.Column('pref_distance', sa.Integer(), nullable=True))
    
    op.execute("UPDATE users SET location='POINT(88.3639 22.5726)';")
    op.execute("UPDATE users SET pref_distance=20;")
    
    op.alter_column('users', 'location', nullable=False)
    op.alter_column('users', 'pref_distance', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pref_distance')
    op.drop_column('users', 'location')
    # ### end Alembic commands ###
