"""Same enums used for schemas & models

Revision ID: c9e55581e45e
Revises: 738cfae4ba0d
Create Date: 2021-04-28 02:48:00.958476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9e55581e45e'
down_revision = '738cfae4ba0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
